const fs=require('fs');
function assert(c,m){if(!c)throw new Error(m)}
const read=p=>fs.readFileSync(p,'utf8');
const html=read('index.html'),game=read('src/game.js'),engine=read('src/engine3d/World3DEngine.js'),content=read('src/content/game-content.js'),terrain=read('src/terrain/terrain-runtime.js'),mesher=read('src/terrain/voxel-block-mesh.js');
assert(html.includes('voxel3d-r16'),'3D voxel build key missing');
assert(html.includes('id="threeWorldLayer"'),'Three.js host missing');
assert(terrain.includes('class TerrainWorld'),'TerrainWorld missing');
assert(terrain.includes('chunkSize=16'),'16^3 voxel chunks missing');
assert(terrain.includes('generateVoxel(gx,gy,gz)'),'3D voxel generation missing');
assert(terrain.includes('peekVoxel(gx,gy,gz)'),'non-loading 3D voxel lookup missing');
assert(terrain.includes('collidesAABB(x,y,z'),'3D voxel collision missing');
assert(terrain.includes('dimensions:3')&&terrain.includes('infinite:true'),'infinite 3D terrain stats missing');
assert(mesher.includes('buildVoxelChunkGeometry'),'3-axis greedy voxel mesher missing');
assert(mesher.includes('for(let d=0;d<3;d++)'),'mesher does not sweep 3 axes');
assert(engine.includes("infinite-3d-voxel-terrain"),'3D chunk renderer missing');
assert(engine.includes("worldMode:'infinite-voxel-3d'"),'wrong world mode');
assert(engine.includes("terrainMode:'streamed-3d-voxel-chunks'"),'wrong terrain mode');
assert(engine.includes('_raycastVoxel(ray,maxDistance=8,{interactionOnly=false}={})'),'voxel DDA raycast missing');
assert(game.includes("keys.has('KeyW')")&&game.includes("keys.has('KeyS')"),'forward/back movement missing');
assert(game.includes("moveAxis('z'"),'Z-axis movement missing');
assert(game.includes('placeTerrainCell')&&game.includes('digTerrainCell'),'3D dig/place missing');
assert(content.includes("mode:'infinite-voxel-3d'"),'3D voxel content mode missing');
assert(content.includes('visibleChunkRadiusXZ'),'3D streaming radius missing');
assert(content.includes('interactionRowZ:0'),'configured interaction row missing');
assert(game.includes("interaction-row-only"),'interaction-row editing guard missing');
assert(engine.includes("mode:'sun-sky-moon-torch'"),'balanced world lighting mode missing');
assert(engine.includes('sun.castShadow=true'),'sun shadowing missing');
assert(engine.includes("visible-sun"),'visible sun mesh missing');
assert(engine.includes('sun.intensity=daylight*3.4'),'daylight sun intensity missing');
assert(engine.includes('sky-environment-bounce'),'sky/environment bounce light missing');
assert(engine.includes('world-moon'),'moonlight missing');
assert(engine.includes('_skyExposureAt(player)'),'sky-exposure cave darkening missing');
assert(terrain.includes("nonInteractionTerrain:'surface-shell-only'"),'non-interaction rows are not surface-only');
assert(terrain.includes('chunkMayContainTerrain'),'empty scenery chunk culling missing');
assert(engine.includes('moving-torch-light'),'moving torch point light missing');
assert(engine.includes('undergroundBackground:\'near-black\''),'underground void background fade missing');
assert(engine.includes('undergroundFactor'),'underground depth fade missing');
assert(content.includes("'hand-torch'"),'torch item definition missing');
assert(game.includes("action==='toggle-torch'"),'torch inventory action missing');
assert(engine.includes('mesh.receiveShadow=true;mesh.castShadow=true'),'voxel chunks must cast and receive sunlight shadows');
assert(engine.includes('interactionOnly:true'),'interaction-only voxel raycast missing');
assert(engine.includes('z===this.interactionRowZ'),'non-interaction rows are not ignored by picking');
assert(html.includes('id="quickbar"')&&html.includes('data-quick-slot="0"'),'visible quickbar missing');
assert(game.includes('activateQuickSlot(index)'),'quickbar activation missing');
assert(game.includes("event.code==='KeyT'"),'torch hotkey missing');
assert(engine.includes('new THREE.PointLight(0xffa24f'),'torch is not a real point light');
assert(engine.includes('this.torch.light.intensity=4.2*flicker'),'torch light intensity missing');
assert(mesher.includes("setAttribute('darkness'"),'underground darkness attribute missing');
assert(mesher.includes('buildUndergroundOcclusionGeometry'),'explicit underground occlusion geometry missing');
assert(engine.includes('uTorchOn'),'torch reveal uniform missing');
assert(engine.includes("terraria-style-light-field-v3"),'integrated Terraria darkness shader missing');
assert(engine.includes('outgoingLight*=darknessVisibility'),'terrain darkness is not integrated into lighting');
assert(engine.includes('uDarkTorchOn'),'torch reveal uniform missing');
assert(engine.includes("terraria-style-full-underground-mask-v4"),'full underground blackout mode missing');
assert(engine.includes('uDarkUnderground'),'underground blackout uniform missing');
assert(engine.includes("terraria-style-los-lightmap-v5"),'LOS voxel lighting mode missing');
assert(engine.includes('_torchLineClear'),'torch line-of-sight test missing');
assert(engine.includes('uVoxelLightMap'),'voxel lightmap uniform missing');
assert(engine.includes('torchLight.castShadow=true'),'torch shadow casting missing');
assert(engine.includes("terraria-cutaway-z-face-mask-v6"),'cutaway-face underground mask missing');
assert(mesher.includes("Math.abs(normal?.[2]||0)<.5"),'darkness must apply only to depth-facing faces');
assert(engine.includes("explicit-black-cutaway-mesh-v7"),'explicit buried cutaway mask missing');
assert(engine.includes('buried-cutaway-mask'),'buried cutaway mesh missing');
assert(mesher.includes("mode:'buried-front-z-faces'"),'buried front-face geometry missing');
console.log('WEB_INFINITE_VOXEL_3D_SMOKE_OK');
