const fs=require('fs');
function assert(c,m){if(!c)throw new Error(m)}
const read=p=>fs.readFileSync(p,'utf8');
const html=read('index.html'),game=read('src/game.js'),engine=read('src/engine3d/World3DEngine.js'),content=read('src/content/game-content.js'),terrain=read('src/terrain/terrain-runtime.js'),mesher=read('src/terrain/voxel-block-mesh.js');
assert(html.includes('voxel3d-r26'),'3D voxel build key missing');
assert(html.includes('id="threeWorldLayer"'),'Three.js host missing');
assert(terrain.includes('class TerrainWorld'),'TerrainWorld missing');
assert(terrain.includes('chunkSize=16'),'16^3 voxel chunks missing');
assert(terrain.includes('generateVoxel(gx,gy,gz)'),'3D voxel generation missing');
assert(terrain.includes('peekVoxel(gx,gy,gz)'),'non-loading 3D voxel lookup missing');
assert(terrain.includes('collidesAABB(x,y,z'),'3D voxel collision missing');
assert(terrain.includes('dimensions:3')&&terrain.includes('infinite:true'),'infinite 3D terrain stats missing');
assert(mesher.includes('buildVoxelChunkGeometry'),'3-axis greedy voxel mesher missing');
assert(mesher.includes('for(let d=0;d<3;d++)'),'mesher does not sweep 3 axes');
assert(engine.includes("infinite-3d-voxel-terrain"),'3D chunk renderer missing');
assert(engine.includes("worldMode:'infinite-voxel-3d'"),'wrong world mode');
assert(engine.includes("terrainMode:'streamed-3d-voxel-chunks'"),'wrong terrain mode');
assert(engine.includes('_raycastVoxel(ray,maxDistance=8,{interactionOnly=false}={})'),'voxel DDA raycast missing');
assert(game.includes('placeTerrainCell')&&game.includes('digTerrainCell'),'3D dig/place missing');
assert(content.includes("mode:'infinite-voxel-3d'"),'3D voxel content mode missing');
assert(content.includes('visibleChunkRadiusXZ'),'3D streaming radius missing');
assert(content.includes('interactionRowZ:0'),'configured interaction row missing');
assert(game.includes("interaction-row-only"),'interaction-row editing guard missing');
assert(engine.includes("mode:'sun-sky-moon-torch'"),'balanced world lighting mode missing');
assert(engine.includes('sun.castShadow=true'),'sun shadowing missing');
assert(engine.includes("visible-sun"),'visible sun mesh missing');
assert(engine.includes('sun.intensity=daylight*3.4'),'daylight sun intensity missing');
assert(engine.includes('sky-environment-bounce'),'sky/environment bounce light missing');
assert(engine.includes('world-moon'),'moonlight missing');
assert(engine.includes('_skyExposureAt(player)'),'sky-exposure cave darkening missing');
assert(terrain.includes('chunkMayContainTerrain'),'empty scenery chunk culling missing');
assert(engine.includes('moving-torch-light'),'moving torch point light missing');
assert(engine.includes('undergroundFactor'),'underground depth fade missing');
assert(content.includes("'hand-torch'"),'torch item definition missing');
assert(game.includes("action==='toggle-torch'"),'torch inventory action missing');
assert(engine.includes('mesh.receiveShadow=true;mesh.castShadow=true'),'voxel chunks must cast and receive sunlight shadows');
assert(engine.includes('interactionOnly:true'),'interaction-only voxel raycast missing');
assert(engine.includes('z===this.interactionRowZ'),'non-interaction rows are not ignored by picking');
assert(html.includes('id="quickbar"')&&html.includes('data-quick-slot="0"'),'visible quickbar missing');
assert(game.includes('activateQuickSlot(index)'),'quickbar activation missing');
assert(game.includes("event.code==='KeyT'"),'torch hotkey missing');
assert(engine.includes('new THREE.PointLight(0xffa24f'),'torch is not a real point light');
assert(engine.includes('this.torch.light.intensity=4.2*flicker'),'torch light intensity missing');
assert(mesher.includes("setAttribute('darkness'"),'underground darkness attribute missing');
assert(engine.includes('outgoingLight*=darknessVisibility'),'terrain darkness is not integrated into lighting');
assert(engine.includes('uDarkTorchOn'),'torch reveal uniform missing');
assert(engine.includes('_torchLineClear'),'torch line-of-sight test missing');
assert(engine.includes('uVoxelLightMap'),'voxel lightmap uniform missing');
assert(engine.includes('torchLight.castShadow=true'),'torch shadow casting missing');
assert(mesher.includes("Math.abs(normal?.[2]||0)<.5"),'darkness must apply only to depth-facing faces');
assert(engine.includes("culled-buried-z-faces-v9"),'buried Z-face culling mode missing');
assert(mesher.includes('if(face&&d===2)'),'buried depth-face culling missing');
assert(!engine.includes('buried-cutaway-mask'),'obsolete black overlay mesh still present');
assert(game.includes('const PLAYER_ROW_CENTER_Z=INTERACTION_ROW_Z*(sceneData.terrain?.tileSize??1);'),'player row center constant missing');
assert(game.includes('transform.z=PLAYER_ROW_CENTER_Z;'),'player is not locked to row center');
assert(game.includes('velocity.z=0;'),'Z velocity is not disabled');
assert(!game.includes("keys.has('KeyW')")&&!game.includes("keys.has('KeyS')"),'W/S Z movement still exists');
assert(terrain.includes('gz:Math.floor(z/s+.5)'),'centered-Z worldToCell missing');
assert(terrain.includes('z:gz*s'),'centered-Z cellCenter missing');
assert(engine.includes('cz*span-this.terrain.tileSize*.5'),'voxel render Z offset missing');
assert(engine.includes("backgroundMode:'fixed-uniform-blue'"),'fixed uniform background mode missing');
assert(engine.includes("backgroundColor:'#6f7fa8'"),'fixed blue background color missing');
assert(!engine.includes('sky.lerp(undergroundVoid'),'background still changes underground');
assert(content.includes('blackBackRowZ:-1'),'rear black voxel row config missing');
assert(terrain.includes('generateBlackBackdropVoxel'),'rear black voxel generation missing');
assert(terrain.includes('gz===this.world.blackBackRowZ'),'rear row is not generated as full-depth voxels');
assert(mesher.includes('new THREE.Color(0x000000)'),'rear row is not absolute black');
assert(mesher.includes('renderCode=solidGz===terrain.blackBackRowZ?tile+32:tile'),'black row render separation missing');
assert(mesher.includes('aGz===terrain.blackBackRowZ&&bGz===terrain.interactionRowZ'),'rear black interface face missing');
assert(engine.includes('undergroundLayers:{count:2'),'two-layer underground stats missing');
assert(terrain.includes('if(gy>surface)return TILE.AIR;'),'rear black row top voxel is still missing');
assert(terrain.includes('if(gy===surface)return TILE.GRASS;'),'rear row top surface is not normal grass');
assert(mesher.includes('buriedBlack=solidGz===terrain.blackBackRowZ&&solidGy<terrain.surfaceCell'),'rear row blackening is not limited to buried voxels');
assert(engine.includes("two-layer-black-back-v10"),'two-layer black backing mode missing');
assert(engine.includes('backgroundProvidesBlack:false'),'background still participates in underground black');
assert(engine.includes('this.scene.background.copy(this.fixedBackgroundColor);')&&engine.includes('this.renderer.setClearColor(this.fixedBackgroundColor,1);'),'render-time fixed blue guarantee missing');
assert(!engine.includes('sun.intensity=daylight*3.4*(1-undergroundFactor'),'sun still dims by underground depth');
assert(!engine.includes('skyFill.intensity=exposed*(1-undergroundFactor'),'sky fill still dims by underground depth');
assert(terrain.includes("rearTopSurface:'normal-grass'"),'rear top surface normal flag missing');
assert(mesher.includes('solidGy<=surface-1'),'rear black is not restricted below surface');
assert(engine.includes("camera-player-capsule-fade-v1"),'camera obstruction fade mode missing');
assert(engine.includes('uOcclusionCamera')&&engine.includes('uOcclusionPlayer'),'terrain camera occlusion uniforms missing');
assert(engine.includes('protectedInteraction')&&engine.includes('protectedBlack'),'protected gameplay rows missing');
assert(engine.includes('entity.material.opacity=state.opacity'),'paper entity obstruction fade missing');
console.log('WEB_INFINITE_VOXEL_3D_SMOKE_OK');
