/* Paperchalk EnvironmentFX v1 — GPU precipitation + atmospheric state machine. */
export class EnvironmentFX{
constructor(THREE,engine){this.THREE=THREE;this.engine=engine;this.scene=engine.scene;this.time=0;this.state='clear';this.target='clear';this.nextChange=30;this.wind=.25;this._build()}
_build(){const T=this.THREE;this.scene.fog=new T.FogExp2(0x93a6b2,.008);this.rain=this._precip(false,1800);this.snow=this._precip(true,900);this.rain.visible=this.snow.visible=false;this.scene.add(this.rain,this.snow);this.clouds=new T.Group();this.clouds.name='paper-cloud-deck';const geo=new T.PlaneGeometry(22,8);for(let i=0;i<10;i++){const m=new T.Mesh(geo,new T.MeshBasicMaterial({color:0xdbe0df,transparent:true,opacity:.08,depthWrite:false,side:T.DoubleSide,toneMapped:false}));m.rotation.x=-Math.PI/2;m.position.set((i%5-2)*18,18+(i*7)%3,Math.floor(i/5)*22-11);m.scale.set(1+(i%3)*.35,1,1);this.clouds.add(m)}this.scene.add(this.clouds)}
_precip(snow,count){const T=this.THREE,p=new Float32Array(count*3),seed=new Float32Array(count);for(let i=0;i<count;i++){p[i*3]=(Math.random()-.5)*34;p[i*3+1]=Math.random()*24;p[i*3+2]=(Math.random()-.5)*18;seed[i]=Math.random()}const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(p,3));g.setAttribute('aSeed',new T.BufferAttribute(seed,1));const mat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uTime:{value:0},uOrigin:{value:new T.Vector3()},uWind:{value:.25},uOpacity:{value:0}},vertexShader:`attribute float aSeed;uniform float uTime;uniform vec3 uOrigin;uniform float uWind;void main(){vec3 p=position;float fall=${snow?'1.2':'13.0'};p.y=mod(p.y-uTime*fall+aSeed*24.0,24.0)-4.0;p.x+=sin(uTime*${snow?'1.7':'0.7'}+aSeed*31.0)*${snow?'1.2':'.18'}+uWind*(20.0-p.y)*.12;p+=uOrigin;vec4 mv=modelViewMatrix*vec4(p,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=${snow?'4.2':'2.0'};}`,fragmentShader:`uniform float uOpacity;void main(){vec2 q=gl_PointCoord-.5;${snow?'if(dot(q,q)>.24)discard;':'if(abs(q.x)>.18)discard;'}gl_FragColor=vec4(${snow?'0.94,0.97,1.0':'0.68,0.82,0.94'},uOpacity);}`});const o=new T.Points(g,mat);o.frustumCulled=false;o.renderOrder=80;return o}
_profile(n){return({clear:[.006,.08,0,0,1,.2],cloudy:[.011,.42,0,0,.78,.4],rain:[.018,.68,.62,0,.62,.75],storm:[.026,.86,.95,0,.42,1.25],snow:[.021,.6,0,.72,.74,.45],blizzard:[.035,.84,0,1,.55,1.4],fog:[.042,.32,0,0,.68,.08]})[n]||this._profile('clear')}
_choose(s){const w=s?.world||{},b=String(w.biome||''),h=+w.elevation||0,cold=b.includes('snow')||b.includes('alpine')||b.includes('pine')&&h>15,r=Math.random();if(cold)return r<.2?'blizzard':r<.62?'snow':r<.78?'cloudy':'clear';if(b==='ocean'||b==='marsh')return r<.16?'storm':r<.55?'rain':r<.76?'cloudy':'clear';return r<.08?'storm':r<.3?'rain':r<.48?'cloudy':r<.54?'fog':'clear'}
update(dt,s){this.time+=dt;this.nextChange-=dt;if(this.nextChange<=0){this.state=this._choose(s);this.nextChange=45+Math.random()*75}const [fog,cloud,rain,snow,light,wind]=this._profile(this.state),p=s?.player||{x:0,y:0,z:0};this.wind+=(wind-this.wind)*Math.min(1,dt*1.5);this.scene.fog.density+=(fog-this.scene.fog.density)*Math.min(1,dt*.8);this.scene.fog.color.setHex(this.state==='storm'?0x66727b:this.state.includes('snow')||this.state==='blizzard'?0xc8d0d2:0x93a6b2);for(const o of [this.rain,this.snow]){o.material.uniforms.uTime.value=this.time;o.material.uniforms.uOrigin.value.set(p.x,p.y,p.z);o.material.uniforms.uWind.value=this.wind}this.rain.material.uniforms.uOpacity.value=rain*.72;this.snow.material.uniforms.uOpacity.value=snow*.86;this.rain.visible=rain>.01;this.snow.visible=snow>.01;this.clouds.position.set(p.x,0,p.z);for(let i=0;i<this.clouds.children.length;i++){const c=this.clouds.children[i];c.material.opacity+=(cloud*.42-c.material.opacity)*Math.min(1,dt);c.position.x+=this.wind*dt*(.7+(i%3)*.15);if(c.position.x>48)c.position.x=-48}const L=this.engine.terrainLights;if(L?.sun)L.sun.intensity*=light;if(L?.skyFill)L.skyFill.intensity*=.72+.28*light;if(L?.ambient)L.ambient.intensity*=.8+.2*light}
stats(){return{state:this.state,fogDensity:this.scene.fog?.density||0,wind:this.wind,rain:this.rain.visible,snow:this.snow.visible,particleMode:'GPU-vertex-shader',rainParticles:1800,snowParticles:900}}
dispose(){for(const o of [this.rain,this.snow]){this.scene.remove(o);o.geometry.dispose();o.material.dispose()}this.clouds.traverse(o=>{o.geometry?.dispose?.();o.material?.dispose?.()});this.scene.remove(this.clouds)}
}
