const VERT=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.0,1.0);}`;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function target(THREE,depth=false){const t=new THREE.WebGLRenderTarget(1,1,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat,type:THREE.UnsignedByteType,depthBuffer:depth,stencilBuffer:false});if(depth){t.depthTexture=new THREE.DepthTexture(1,1,THREE.UnsignedIntType);t.depthTexture.format=THREE.DepthFormat;t.depthTexture.type=THREE.UnsignedIntType;t.depthTexture.minFilter=THREE.NearestFilter;t.depthTexture.magFilter=THREE.NearestFilter}return t}
export class PhotonWaterPass{
 constructor(THREE,{renderer,scene,camera,mobileLike=false}={}){
  this.THREE=THREE;this.renderer=renderer;this.scene=scene;this.camera=camera;this.mobileLike=!!mobileLike;
  this.settings={enabled:true,ssr:true,refraction:true,waves:true,steps:this.mobileLike?10:18,thickness:.018,reflectionStrength:.58,refractionStrength:.018,roughness:.16};
  this.size={w:1,h:1};this.maskTarget=target(THREE,true);this.outputTarget=target(THREE,false);this.fsCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);this.geometry=new THREE.PlaneGeometry(2,2);
  this.maskMaterial=new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide,depthWrite:true,depthTest:true,toneMapped:false});
  this.invViewProj=new THREE.Matrix4();this.viewProj=new THREE.Matrix4();
  this.material=new THREE.ShaderMaterial({uniforms:{tScene:{value:null},tSceneDepth:{value:null},tWaterMask:{value:this.maskTarget.texture},tWaterDepth:{value:this.maskTarget.depthTexture},uInvViewProj:{value:this.invViewProj},uViewProj:{value:this.viewProj},uCameraPos:{value:new THREE.Vector3()},uResolution:{value:new THREE.Vector2(1,1)},uTime:{value:0},uSteps:{value:this.settings.steps},uThickness:{value:this.settings.thickness},uReflectionStrength:{value:this.settings.reflectionStrength},uRefractionStrength:{value:this.settings.refractionStrength},uRoughness:{value:this.settings.roughness},uSSR:{value:1},uRefraction:{value:1},uWaves:{value:1}},depthTest:false,depthWrite:false,toneMapped:false,vertexShader:VERT,fragmentShader:`
precision highp float;varying vec2 vUv;uniform sampler2D tScene,tSceneDepth,tWaterMask,tWaterDepth;uniform mat4 uInvViewProj,uViewProj;uniform vec3 uCameraPos;uniform vec2 uResolution;uniform float uTime,uSteps,uThickness,uReflectionStrength,uRefractionStrength,uRoughness,uSSR,uRefraction,uWaves;
vec3 worldPos(vec2 uv,float d){vec4 c=vec4(uv*2.0-1.0,d*2.0-1.0,1.0);vec4 w=uInvViewProj*c;return w.xyz/max(1e-6,w.w);}vec3 projectUv(vec3 p){vec4 c=uViewProj*vec4(p,1.0);vec3 n=c.xyz/max(1e-6,c.w);return vec3(n.xy*.5+.5,n.z*.5+.5);}float wave(vec2 p,float t){float a=sin(dot(p,vec2(.72,.34))*2.1+t*1.15);float b=sin(dot(p,vec2(-.28,.93))*3.4-t*.83);float c=sin(dot(p,vec2(.89,-.45))*5.7+t*1.72);return a*.48+b*.32+c*.20;}vec3 waterNormal(vec3 p,vec3 flatN){float h=.08;float w0=wave(p.xz,uTime),wx=wave(p.xz+vec2(h,0),uTime),wz=wave(p.xz+vec2(0,h),uTime);vec3 n=normalize(flatN+vec3((wx-w0)*.42,0.0,(wz-w0)*.42)*uWaves);if(n.y<0.0)n=-n;return n;}
void main(){vec3 base=texture2D(tScene,vUv).rgb;float mask=texture2D(tWaterMask,vUv).r;if(mask<.5){gl_FragColor=vec4(base,1.0);return;}float wd=texture2D(tWaterDepth,vUv).x;vec2 px=1.0/uResolution;vec3 p=worldPos(vUv,wd);float dx=texture2D(tWaterDepth,vUv+vec2(px.x,0)).x,dy=texture2D(tWaterDepth,vUv+vec2(0,px.y)).x;vec3 pxw=worldPos(vUv+vec2(px.x,0),dx),pyw=worldPos(vUv+vec2(0,px.y),dy);vec3 n=normalize(cross(pxw-p,pyw-p));if(n.y<0.0)n=-n;n=waterNormal(p,n);vec3 viewDir=normalize(p-uCameraPos);float NoV=clamp(dot(-viewDir,n),0.0,1.0);float fresnel=.02+.98*pow(1.0-NoV,5.0);
vec2 refrUv=clamp(vUv+n.xz*uRefractionStrength*(.25+.75*(1.0-NoV)),vec2(.002),vec2(.998));vec3 refr=texture2D(tScene,refrUv).rgb;vec3 refl=vec3(.26,.42,.62);float hit=0.0;vec3 rd=normalize(reflect(viewDir,n));float travel=.22;float jitter=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453);travel+=jitter*.18;
for(int i=0;i<24;i++){if(float(i)>=uSteps||hit>.5)break;travel+=.26+travel*.085;vec3 q=p+rd*travel;vec3 ss=projectUv(q);if(any(lessThan(ss.xy,vec2(.002)))||any(greaterThan(ss.xy,vec2(.998)))||ss.z<0.0||ss.z>1.0)break;float sd=texture2D(tSceneDepth,ss.xy).x;if(sd>=.99995)continue;float dz=ss.z-sd;float tol=uThickness+travel*.0009;if(dz>0.0&&dz<tol){refl=texture2D(tScene,ss.xy).rgb;float edge=1.0-smoothstep(.74,1.0,max(abs(ss.x-.5),abs(ss.y-.5))*2.0);hit=edge;}}
float reflectAmt=fresnel*uReflectionStrength*uSSR*mix(.5,1.0,hit)*(1.0-uRoughness*.55);vec3 waterBase=mix(base,refr,uRefraction*.72);waterBase=mix(waterBase,waterBase*vec3(.78,.93,1.05),.22);vec3 outc=mix(waterBase,refl,clamp(reflectAmt,0.0,.78));gl_FragColor=vec4(outc,1.0);}`});
  this.passScene=new THREE.Scene();this.mesh=new THREE.Mesh(this.geometry,this.material);this.passScene.add(this.mesh);this.renders=0;this.maskRenders=0;
 }
 configure(p={}){Object.assign(this.settings,p||{});this.settings.steps=Math.round(clamp(Number(this.settings.steps)||12,6,24));this.settings.thickness=clamp(Number(this.settings.thickness)||.018,.004,.08);this.settings.reflectionStrength=clamp(Number(this.settings.reflectionStrength)||.58,0,1.2);this.settings.refractionStrength=clamp(Number(this.settings.refractionStrength)||.018,0,.08);this.settings.roughness=clamp(Number(this.settings.roughness)||.16,0,.9);return this.stats()}
 resize(w,h){w=Math.max(1,Math.round(w||1));h=Math.max(1,Math.round(h||1));if(w===this.size.w&&h===this.size.h)return;this.size={w,h};this.maskTarget.setSize(w,h);this.outputTarget.setSize(w,h);this.material.uniforms.uResolution.value.set(w,h)}
 _renderMask(){const root=this.scene.getObjectByName('eight-layer-water-surface-meshes');if(!root||root.visible===false)return false;const states=this.scene.children.map(o=>[o,o.visible]);const oldOverride=this.scene.overrideMaterial,oldBg=this.scene.background,oldTarget=this.renderer.getRenderTarget(),oldAuto=this.renderer.autoClear;try{for(const [o] of states)o.visible=o===root;root.visible=true;this.scene.overrideMaterial=this.maskMaterial;this.scene.background=null;this.renderer.setRenderTarget(this.maskTarget);this.renderer.autoClear=true;this.renderer.setClearColor(0x000000,0);this.renderer.clear(true,true,true);this.renderer.render(this.scene,this.camera);this.maskRenders++;return true}finally{for(const [o,v] of states)o.visible=v;this.scene.overrideMaterial=oldOverride;this.scene.background=oldBg;this.renderer.setRenderTarget(oldTarget);this.renderer.autoClear=oldAuto}}
 render({sceneTexture,sceneDepth,time=0}={}){if(!this.settings.enabled||!sceneTexture||!sceneDepth)return sceneTexture;if(!this._renderMask())return sceneTexture;this.camera.updateMatrixWorld();this.viewProj.multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse);this.invViewProj.copy(this.viewProj).invert();const u=this.material.uniforms;u.tScene.value=sceneTexture;u.tSceneDepth.value=sceneDepth;u.uCameraPos.value.copy(this.camera.position);u.uTime.value=Number(time)||0;u.uSteps.value=this.settings.steps;u.uThickness.value=this.settings.thickness;u.uReflectionStrength.value=this.settings.reflectionStrength;u.uRefractionStrength.value=this.settings.refractionStrength;u.uRoughness.value=this.settings.roughness;u.uSSR.value=this.settings.ssr?1:0;u.uRefraction.value=this.settings.refraction?1:0;u.uWaves.value=this.settings.waves?1:0;const old=this.renderer.getRenderTarget(),auto=this.renderer.autoClear;this.renderer.setRenderTarget(this.outputTarget);this.renderer.autoClear=true;this.renderer.setClearColor(0x000000,1);this.renderer.clear(true,false,false);this.renderer.render(this.passScene,this.fsCamera);this.renderer.setRenderTarget(old);this.renderer.autoClear=auto;this.renders++;return this.outputTarget.texture}
 stats(){return {enabled:!!this.settings.enabled,mode:'photon-water-ssr-r1',ssr:!!this.settings.ssr,screenSpaceRaymarch:true,refraction:!!this.settings.refraction,gerstnerStyleWaves:!!this.settings.waves,variableFresnel:true,steps:this.settings.steps,renders:this.renders,maskRenders:this.maskRenders}}
 dispose(){this.maskTarget.dispose();this.outputTarget.dispose();this.maskMaterial.dispose();this.material.dispose();this.geometry.dispose()}
}
