const VERT=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.0,1.0);}`;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
export class PhotonVoxelLightVolume{
 constructor(THREE,{renderer,scene,camera,mobileLike=false}={}){
  this.THREE=THREE;this.renderer=renderer;this.scene=scene;this.camera=camera;this.mobileLike=!!mobileLike;this.terrain=globalThis.PaperchalkTerrain||null;
  this.nx=this.mobileLike?19:25;this.ny=this.mobileLike?13:17;this.nz=this.mobileLike?7:9;this.count=this.nx*this.ny*this.nz;this.data=new Uint8Array(this.count*4);this.solid=new Uint8Array(this.count);this.light=new Float32Array(this.count*3);this.origin={x:0,y:0,z:0};this.lastKey='';this.lastUpdate=0;this.version=0;
  this.texture=new THREE.DataTexture(this.data,this.nx,this.ny*this.nz,THREE.RGBAFormat,THREE.UnsignedByteType);this.texture.minFilter=THREE.LinearFilter;this.texture.magFilter=THREE.LinearFilter;this.texture.generateMipmaps=false;this.texture.needsUpdate=true;
  this.target=new THREE.WebGLRenderTarget(1,1,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat,type:THREE.UnsignedByteType,depthBuffer:false,stencilBuffer:false});this.size={w:1,h:1};
  this.invViewProj=new THREE.Matrix4();this.material=new THREE.ShaderMaterial({uniforms:{tScene:{value:null},tDepth:{value:null},tVolume:{value:this.texture},uInvViewProj:{value:this.invViewProj},uOrigin:{value:new THREE.Vector3()},uDims:{value:new THREE.Vector3(this.nx,this.ny,this.nz)},uResolution:{value:new THREE.Vector2(1,1)},uStrength:{value:this.mobileLike?.22:.30}},depthTest:false,depthWrite:false,toneMapped:false,vertexShader:VERT,fragmentShader:`
precision highp float;varying vec2 vUv;uniform sampler2D tScene,tDepth,tVolume;uniform mat4 uInvViewProj;uniform vec3 uOrigin,uDims;uniform vec2 uResolution;uniform float uStrength;
vec3 worldPos(vec2 uv,float d){vec4 c=vec4(uv*2.0-1.0,d*2.0-1.0,1.0);vec4 w=uInvViewProj*c;return w.xyz/max(1e-6,w.w);}vec3 sampleV(vec3 p){vec3 q=floor(p-uOrigin);if(any(lessThan(q,vec3(0)))||any(greaterThanEqual(q,uDims)))return vec3(0);float row=q.z*uDims.y+q.y;vec2 uv=vec2((q.x+.5)/uDims.x,(row+.5)/(uDims.y*uDims.z));return texture2D(tVolume,uv).rgb;}
void main(){vec3 base=texture2D(tScene,vUv).rgb;float d=texture2D(tDepth,vUv).x;if(d>=.99998){gl_FragColor=vec4(base,1);return;}vec2 px=1.0/uResolution;vec3 p=worldPos(vUv,d);vec3 pr=worldPos(vUv+vec2(px.x,0),texture2D(tDepth,vUv+vec2(px.x,0)).x);vec3 pu=worldPos(vUv+vec2(0,px.y),texture2D(tDepth,vUv+vec2(0,px.y)).x);vec3 n=normalize(cross(pr-p,pu-p));vec3 l=sampleV(p+n*.42);l=max(l,sampleV(p+n*.85));float m=max(max(l.r,l.g),l.b);vec3 outc=base+l*uStrength*(.55+.45*clamp(abs(n.y),0.0,1.0))*(.7+.3*m);gl_FragColor=vec4(outc,1);}`});
  this.fsCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);this.geometry=new THREE.PlaneGeometry(2,2);this.passScene=new THREE.Scene();this.passScene.add(new THREE.Mesh(this.geometry,this.material));this.renders=0;
 }
 _idx(x,y,z){return (z*this.ny+y)*this.nx+x}
 _emitters(){const out=[];this.scene?.traverse?.(o=>{if(!o?.isPointLight||!o.visible||o.intensity<=.02||out.length>=6)return;const p=new this.THREE.Vector3();o.getWorldPosition(p);out.push({p,c:o.color.clone(),power:clamp(o.intensity/4.2,.15,1.5),radius:Math.min(14,Math.max(3,Number(o.distance)||10))})});return out}
 _updateVolume(now=performance.now()){
  if(!this.terrain)return;const emit=this._emitters();const focus=emit[0]?.p||this.camera.position;const gx=Math.floor(focus.x),gy=Math.floor(focus.y),gz=Math.floor(focus.z);const key=[gx,gy,gz,emit.map(e=>e.power.toFixed(2)).join(','),this.terrain.changeVersion||0].join('|');if(key===this.lastKey&&now-this.lastUpdate<140)return;this.lastKey=key;this.lastUpdate=now;this.origin.x=gx-(this.nx>>1);this.origin.y=gy-(this.ny>>1);this.origin.z=gz-(this.nz>>1);this.solid.fill(0);this.light.fill(0);
  for(let z=0;z<this.nz;z++)for(let y=0;y<this.ny;y++)for(let x=0;x<this.nx;x++){const i=this._idx(x,y,z),wx=this.origin.x+x,wy=this.origin.y+y,wz=this.origin.z+z;this.solid[i]=this.terrain.isSolidPeek?.(wx,wy,wz)?1:0}
  const dirs=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];for(const e of emit){const sx=Math.floor(e.p.x)-this.origin.x,sy=Math.floor(e.p.y)-this.origin.y,sz=Math.floor(e.p.z)-this.origin.z;if(sx<0||sy<0||sz<0||sx>=this.nx||sy>=this.ny||sz>=this.nz)continue;const q=[[sx,sy,sz,1]],best=new Float32Array(this.count);best[this._idx(sx,sy,sz)]=1;for(let qi=0;qi<q.length&&qi<5000;qi++){const [x,y,z,v]=q[qi],i=this._idx(x,y,z),fall=v*e.power;this.light[i*3]+=e.c.r*fall;this.light[i*3+1]+=e.c.g*fall;this.light[i*3+2]+=e.c.b*fall;if(v<.07)continue;for(const d of dirs){const nx=x+d[0],ny=y+d[1],nz=z+d[2];if(nx<0||ny<0||nz<0||nx>=this.nx||ny>=this.ny||nz>=this.nz)continue;const ni=this._idx(nx,ny,nz);if(this.solid[ni])continue;const nv=v*.78;if(nv<=best[ni]+.025)continue;best[ni]=nv;q.push([nx,ny,nz,nv])}}}
  for(let i=0;i<this.count;i++){const o=i*4;this.data[o]=Math.min(255,Math.round(Math.sqrt(clamp(this.light[i*3],0,1))*255));this.data[o+1]=Math.min(255,Math.round(Math.sqrt(clamp(this.light[i*3+1],0,1))*255));this.data[o+2]=Math.min(255,Math.round(Math.sqrt(clamp(this.light[i*3+2],0,1))*255));this.data[o+3]=255}this.texture.needsUpdate=true;this.version++;
 }
 resize(w,h){w=Math.max(1,Math.round(w||1));h=Math.max(1,Math.round(h||1));if(w===this.size.w&&h===this.size.h)return;this.size={w,h};this.target.setSize(w,h);this.material.uniforms.uResolution.value.set(w,h)}
 render({sceneTexture,sceneDepth}={}){if(!sceneTexture||!sceneDepth)return sceneTexture;this._updateVolume();this.camera.updateMatrixWorld();this.invViewProj.multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse).invert();const u=this.material.uniforms;u.tScene.value=sceneTexture;u.tDepth.value=sceneDepth;u.uInvViewProj.value.copy(this.invViewProj);u.uOrigin.value.set(this.origin.x,this.origin.y,this.origin.z);const old=this.renderer.getRenderTarget(),auto=this.renderer.autoClear;this.renderer.setRenderTarget(this.target);this.renderer.autoClear=true;this.renderer.setClearColor(0,1);this.renderer.clear(true,false,false);this.renderer.render(this.passScene,this.fsCamera);this.renderer.setRenderTarget(old);this.renderer.autoClear=auto;this.renders++;return this.target.texture}
 stats(){return {mode:'photon-rgb-voxel-light-volume-r1',enabled:true,dimensions:[this.nx,this.ny,this.nz],cpuFloodFill:true,sixNeighbourPropagation:true,pointLightEmitters:true,version:this.version,renders:this.renders}}
 dispose(){this.texture.dispose();this.target.dispose();this.material.dispose();this.geometry.dispose()}
}
