const VERT=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.0,1.0);}`;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function target(THREE,depth=false){const t=new THREE.WebGLRenderTarget(1,1,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat,type:THREE.UnsignedByteType,depthBuffer:depth,stencilBuffer:false});if(depth){t.depthTexture=new THREE.DepthTexture(1,1,THREE.UnsignedIntType);t.depthTexture.format=THREE.DepthFormat;t.depthTexture.type=THREE.UnsignedIntType}return t}
export class PhotonSpecularSSRPass{
  constructor(THREE,{renderer,scene,camera,mobileLike=false}={}){
    this.THREE=THREE;this.renderer=renderer;this.scene=scene;this.camera=camera;this.mobileLike=!!mobileLike;
    this.settings={enabled:true,steps:this.mobileLike?8:14,thickness:.015,strength:.46,minReflectivity:.08};
    this.maskTarget=target(THREE,true);this.outputTarget=target(THREE);this.size={w:1,h:1};this.viewProj=new THREE.Matrix4();this.invViewProj=new THREE.Matrix4();
    this.fsCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);this.geometry=new THREE.PlaneGeometry(2,2);this.maskCache=new Map();this.renderCount=0;this.maskCount=0;
    this.material=new THREE.ShaderMaterial({uniforms:{tScene:{value:null},tDepth:{value:null},tMask:{value:this.maskTarget.texture},uInvViewProj:{value:this.invViewProj},uViewProj:{value:this.viewProj},uCameraPos:{value:new THREE.Vector3()},uResolution:{value:new THREE.Vector2(1,1)},uSteps:{value:this.settings.steps},uThickness:{value:this.settings.thickness},uStrength:{value:this.settings.strength}},depthTest:false,depthWrite:false,toneMapped:false,vertexShader:VERT,fragmentShader:`
precision highp float;varying vec2 vUv;uniform sampler2D tScene,tDepth,tMask;uniform mat4 uInvViewProj,uViewProj;uniform vec3 uCameraPos;uniform vec2 uResolution;uniform float uSteps,uThickness,uStrength;
vec3 worldPos(vec2 uv,float d){vec4 c=vec4(uv*2.0-1.0,d*2.0-1.0,1.0);vec4 w=uInvViewProj*c;return w.xyz/max(1e-6,w.w);}vec3 projectP(vec3 p){vec4 c=uViewProj*vec4(p,1.0);vec3 n=c.xyz/max(1e-6,c.w);return vec3(n.xy*.5+.5,n.z*.5+.5);}
void main(){vec3 base=texture2D(tScene,vUv).rgb;float reflectivity=texture2D(tMask,vUv).r;if(reflectivity<.025){gl_FragColor=vec4(base,1);return;}float d=texture2D(tDepth,vUv).x;if(d>=.99995){gl_FragColor=vec4(base,1);return;}vec2 px=1.0/uResolution;vec3 p=worldPos(vUv,d),pr=worldPos(vUv+vec2(px.x,0),texture2D(tDepth,vUv+vec2(px.x,0)).x),pu=worldPos(vUv+vec2(0,px.y),texture2D(tDepth,vUv+vec2(0,px.y)).x);vec3 n=normalize(cross(pr-p,pu-p));vec3 v=normalize(p-uCameraPos);if(dot(n,-v)<0.0)n=-n;vec3 rd=normalize(reflect(v,n));float fresnel=.04+.96*pow(1.0-clamp(dot(-v,n),0.0,1.0),5.0);vec3 hitColor=base;float hit=0.0,travel=.12;
for(int i=0;i<20;i++){if(float(i)>=uSteps||hit>.5)break;travel+=.18+travel*.11;vec3 ss=projectP(p+rd*travel);if(any(lessThan(ss.xy,vec2(.003)))||any(greaterThan(ss.xy,vec2(.997)))||ss.z<=0.0||ss.z>=1.0)break;float sd=texture2D(tDepth,ss.xy).x;if(sd>=.99995)continue;float dz=ss.z-sd,tol=uThickness+travel*.0012;if(dz>0.0&&dz<tol){float edge=1.0-smoothstep(.68,1.0,max(abs(ss.x-.5),abs(ss.y-.5))*2.0);hitColor=texture2D(tScene,ss.xy).rgb;hit=edge;}}
float amount=clamp(reflectivity*uStrength*(.25+.75*fresnel)*hit,0.0,.72);gl_FragColor=vec4(mix(base,hitColor,amount),1);}`});
    this.passScene=new THREE.Scene();this.passScene.add(new THREE.Mesh(this.geometry,this.material));
  }
  _scoreMaterial(m){if(!m||m.visible===false||m.transparent&&Number(m.opacity)<.2)return 0;const rough=Number.isFinite(m.roughness)?m.roughness:1,metal=Number.isFinite(m.metalness)?m.metalness:0,env=Number.isFinite(m.envMapIntensity)?m.envMapIntensity:0;return clamp((1-rough)*.75+metal*.75+env*.08,0,1)}
  _maskMaterial(score){const key=Math.round(score*16)/16;if(!this.maskCache.has(key))this.maskCache.set(key,new this.THREE.MeshBasicMaterial({color:new this.THREE.Color(key,key,key),side:this.THREE.DoubleSide,depthWrite:true,depthTest:true,toneMapped:false}));return this.maskCache.get(key)}
  _renderMask(){const swapped=[];this.scene.traverse(o=>{if(!o?.isMesh||o.visible===false)return;const name=String(o.name||'');if(name.includes('water')||name.includes('sky')||name==='visible-sun'||name==='visible-moon')return;const mats=Array.isArray(o.material)?o.material:[o.material];let score=0;for(const m of mats)score=Math.max(score,this._scoreMaterial(m));if(score<this.settings.minReflectivity)return;swapped.push([o,o.material]);o.material=this._maskMaterial(score)});
    if(!swapped.length)return false;const oldTarget=this.renderer.getRenderTarget(),oldAuto=this.renderer.autoClear,oldBg=this.scene.background;const states=[];this.scene.traverse(o=>{if(o?.isMesh&& !swapped.some(x=>x[0]===o)){states.push([o,o.visible]);o.visible=false}});try{this.scene.background=null;this.renderer.setRenderTarget(this.maskTarget);this.renderer.autoClear=true;this.renderer.setClearColor(0,0);this.renderer.clear(true,true,true);this.renderer.render(this.scene,this.camera);this.maskCount++;return true}finally{for(const [o,m] of swapped)o.material=m;for(const [o,v] of states)o.visible=v;this.scene.background=oldBg;this.renderer.setRenderTarget(oldTarget);this.renderer.autoClear=oldAuto}}
  configure(patch={}){Object.assign(this.settings,patch||{});this.settings.steps=Math.round(clamp(Number(this.settings.steps)||12,4,20));this.settings.thickness=clamp(Number(this.settings.thickness)||.015,.003,.08);this.settings.strength=clamp(Number(this.settings.strength)||.46,0,1.2);this.settings.minReflectivity=clamp(Number(this.settings.minReflectivity)||.08,0,1);return this.stats()}
  resize(w,h){w=Math.max(1,Math.round(w||1));h=Math.max(1,Math.round(h||1));if(w===this.size.w&&h===this.size.h)return;this.size={w,h};this.maskTarget.setSize(w,h);this.outputTarget.setSize(w,h);this.material.uniforms.uResolution.value.set(w,h)}
  render({sceneTexture,sceneDepth}={}){if(!this.settings.enabled||!sceneTexture||!sceneDepth)return sceneTexture;if(!this._renderMask())return sceneTexture;this.camera.updateMatrixWorld();this.viewProj.multiplyMatrices(this.camera.projectionMatrix,this.camera.matrixWorldInverse);this.invViewProj.copy(this.viewProj).invert();const u=this.material.uniforms;u.tScene.value=sceneTexture;u.tDepth.value=sceneDepth;u.uInvViewProj.value.copy(this.invViewProj);u.uViewProj.value.copy(this.viewProj);u.uCameraPos.value.copy(this.camera.position);u.uSteps.value=this.settings.steps;u.uThickness.value=this.settings.thickness;u.uStrength.value=this.settings.strength;const old=this.renderer.getRenderTarget(),auto=this.renderer.autoClear;this.renderer.setRenderTarget(this.outputTarget);this.renderer.autoClear=true;this.renderer.setClearColor(0,1);this.renderer.clear(true,false,false);this.renderer.render(this.passScene,this.fsCamera);this.renderer.setRenderTarget(old);this.renderer.autoClear=auto;this.renderCount++;return this.outputTarget.texture}
  stats(){return {mode:'photon-material-ssr-r1',enabled:!!this.settings.enabled,materialMask:true,screenSpaceRaymarch:true,roughnessMetalnessMask:true,waterSeparate:true,steps:this.settings.steps,renders:this.renderCount,maskRenders:this.maskCount}}
  dispose(){this.maskTarget.dispose();this.outputTarget.dispose();this.material.dispose();this.geometry.dispose();for(const m of this.maskCache.values())m.dispose();this.maskCache.clear()}
}
